import { ApplicationConfig, provideZonelessChangeDetection } from '@angular/core';
import { provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideServiceWorker } from '@angular/service-worker';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import {
  LoginOutline,
  UserAddOutline,
  UserOutline,
  MailOutline,
  ShopOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ThunderboltOutline,
  LockOutline,
  EyeOutline,
  EyeInvisibleOutline,
  PieChartOutline,
  DesktopOutline,
  WifiOutline,
  ApartmentOutline,
  ReloadOutline,
  PlusOutline,
  MinusOutline,
  SendOutline,
  SaveOutline,
  ProjectOutline,
  SearchOutline,
  BellOutline,
  FolderOutline,
  TeamOutline,
  FileTextOutline,
  SettingOutline,
  ProfileOutline,
  MessageOutline,
  BarChartOutline,
  SafetyCertificateOutline,
  RiseOutline,
  NotificationOutline,
  PlayCircleOutline,
  BookOutline,
  MobileOutline,
  ExperimentOutline,
  SwapOutline,
  EllipsisOutline,
  UnorderedListOutline,
  AppstoreOutline,
  EnvironmentOutline,
  PhoneOutline,
  InfoCircleOutline,
  DatabaseOutline,
  ClusterOutline,
  EditOutline,
  DeleteOutline,
} from '@ant-design/icons-angular/icons';
import { routes } from './app.routes';

const nzIcons = [
  LoginOutline,
  UserAddOutline,
  UserOutline,
  MailOutline,
  ShopOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ThunderboltOutline,
  LockOutline,
  EyeOutline,
  EyeInvisibleOutline,
  PieChartOutline,
  DesktopOutline,
  WifiOutline,
  ApartmentOutline,
  ReloadOutline,
  PlusOutline,
  MinusOutline,
  SendOutline,
  SaveOutline,
  ProjectOutline,
  SearchOutline,
  BellOutline,
  FolderOutline,
  TeamOutline,
  FileTextOutline,
  SettingOutline,
  ProfileOutline,
  MessageOutline,
  BarChartOutline,
  SafetyCertificateOutline,
  RiseOutline,
  NotificationOutline,
  PlayCircleOutline,
  BookOutline,
  MobileOutline,
  ExperimentOutline,
  SwapOutline,
  EllipsisOutline,
  UnorderedListOutline,
  AppstoreOutline,
  EnvironmentOutline,
  PhoneOutline,
  InfoCircleOutline,
  DatabaseOutline,
  ClusterOutline,
  EditOutline,
  DeleteOutline,
];

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(withFetch()),
    provideAnimations(),
    provideNzIcons(nzIcons),
    provideServiceWorker('ngsw-worker.js', {
      enabled: true,
      registrationStrategy: 'registerWhenStable:30000',
    }),
  ],
};
